HotelBooking/Areas/Dashboard/ViewModels/StayTypeModels.cs
using HotelBooking.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace HotelBooking.Areas.Dashboard.ViewModels
{
    public class StayTypeListingModels
    {
        public IEnumerable <StayType> StayTypes { get; set; }
        public string SerchTerm { get;  set; }
    }

   

    public class StayTypeActionModels
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public string Desc { get; set; }
    }

}

HotelBooking/Areas/Dashboard/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HotelBooking.Areas.Dashboard.Controllers
{
    public class DashboardController : Controller
    {
        // GET: Dashboard/Dashboard
        public ActionResult Index()
        {
            return View();
        }
    }
}

HotelBooking/Areas/Dashboard/Controllers/StayTypeController.cs
using HotelBooking.Areas.Dashboard.ViewModels;
using HotelBooking.Entities;
using HotelBookingService;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HotelBooking.Areas.Dashboard.Controllers
{
   

    public class StayTypeController : Controller
    {
       
        StayTypeService StayTypeService = new StayTypeService();
       
        public ActionResult Index(string serchTerm)
        {

            StayTypeListingModels model = new StayTypeListingModels();

            model.SerchTerm = serchTerm;

            model.StayTypes = StayTypeService.SearchStayType(serchTerm);

            return View(model);
            
        }

        [HttpGet]
        public ActionResult Action(int? Id)
        {
            StayTypeActionModels model = new StayTypeActionModels();

            if (Id.HasValue)
            {
                var staytype = StayTypeService.GetStayTypeById(Id.Value);
                model.Id = staytype.Id;
                model.Name = staytype.Name;
                model.Desc = staytype.Desc;
              
            }
           

            return PartialView("_Action", model);
        }

        [HttpPost]
        public JsonResult Action(StayTypeActionModels model)
        {
            JsonResult json = new JsonResult();
            var result = false;
            if (model.Id > 0)
            {
                var staytype = StayTypeService.GetStayTypeById(model.Id);
                staytype.Name = model.Name;
                staytype.Desc = model.Desc;

                result = StayTypeService.UpdateStayType(staytype);
            }
            else
            {
                StayType stayType = new StayType();

                stayType.Name = model.Name;
                stayType.Desc = model.Desc;

                result = StayTypeService.SaveStayType(stayType);
            }
         

            if (result)
            {
                json.Data = new { Success = true };
            }
            else{
                json.Data = new { Success = false,  Message = "Xəta!" };
            }

            return json;
        }
        [HttpGet]
        public ActionResult Delete(int Id)
        {
            StayTypeActionModels model = new StayTypeActionModels();

            var staytype = StayTypeService.GetStayTypeById(Id);

            model.Id = staytype.Id;
           


            return PartialView("_Delete", model);
        }
        [HttpPost]
        public JsonResult Delete(StayTypeActionModels model)
        {
            JsonResult json = new JsonResult();
            var result = false;

            var staytype = StayTypeService.GetStayTypeById(model.Id);
           

            result = StayTypeService.DeleteStayType(staytype);


            if (result)
            {
                json.Data = new { Success = true };
            }
            else
            {
                json.Data = new { Success = false, Message = "Xəta!" };
            }

            return json;
        }
    }
}

HotelBooking/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HotelBooking.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

HotelBooking/Areas/Dashboard/Views/Dashboard/Index.cshtml
<h1 class="mt-4">Simple Sidebar</h1>
<p>The starting state of the menu will appear collapsed on smaller screens, and will appear non-collapsed on larger screens. When toggled using the button below, the menu will change.</p>
<p>Make sure to keep all page content within the <code>#page-content-wrapper</code>. The top navbar is optional, and just for demonstration. Just create an element with the <code>#menu-toggle</code> ID which will toggle the menu when clicked.</p>

HotelBooking/Areas/Dashboard/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>@ViewBag.Title - HotelBooking</title>
    <!-- Bootstrap core CSS -->
    <!-- Custom styles for this template -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.2/css/all.min.css" />
    <link href="~/Areas/Dashboard/Public/css/simple-sidebar.css" rel="stylesheet" />
    <link href="~/Areas/Dashboard/Public/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet" />

    <script src="~/Areas/Dashboard/Public/vendor/jquery/jquery.min.js"></script>
</head>

<body>

    <div class="d-flex" id="wrapper">

        <!-- Sidebar -->
        <div class="bg-light border-right" id="sidebar-wrapper">
            <div class="sidebar-heading">Hotel Booking </div>
            <div class="list-group list-group-flush">
                <a href="@Url.Action("Index", "StayType")" class="list-group-item list-group-item-action bg-light"><i class="far fa-building mr-1"></i>Otaqlar</a>
                <a href="@Url.Action("Index", "Roles")" class="list-group-item list-group-item-action bg-light"><i class="fas fa-shield-alt"></i>Roles</a>
                <a href="@Url.Action("Index", "Users")" class="list-group-item list-group-item-action bg-light"><i class="fas fa-users mr-1"></i>Users</a>
            </div>
        </div>
        <!-- /#sidebar-wrapper -->
        <!-- Page Content -->
        <div id="page-content-wrapper">

            <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
                <button class="btn btn-primary" id="menu-toggle"><i class="fas fa-bars"></i></button>

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
                        <li class="nav-item active">
                        
                        </li>
                        
                  
                    </ul>
                </div>
            </nav>

            <div class="container-fluid">

                @RenderBody()

               
            </div>
        </div>
        <!-- /#page-content-wrapper -->

    </div>
    <!-- /#wrapper -->
    <!-- Bootstrap core JavaScript -->
    
    <script src="~/Areas/Dashboard/Public/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Menu Toggle Script -->
    <script>
    $("#menu-toggle").click(function(e) {
      e.preventDefault();
      $("#wrapper").toggleClass("toggled");
    });
    </script>

</body>

</html>

HotelBooking/Areas/Dashboard/Views/StayType/Index.cshtml
@model HotelBooking.Areas.Dashboard.ViewModels.StayTypeListingModels
@{
    ViewBag.Title = "Index";
}

<div class="row">
    <div class="col-lg-12">
        @{ Html.RenderPartial("_Listenig",Model);}
    </div>
</div>

<div class="row mb-3">
    <div class="col-lg-12">
      
            <form>
                <div class="input-group">
                   
                        <input type="text" name="serchterm" class="form-control" placeholder="Axtar" value="@Model.SerchTerm" required />
                        <div class="input-group-append">
                            <button class="btn btn-outline-primary" type="submit">Serach</button>
                            <a class="btn btn-outline-secondary" href="@Url.Action("Index", "StayType")">Reset</a>
                            <button data-href="@Url.Action("Action", "StayType")" class=" data-btn btn btn-outline-success" type="button" data-toggle="modal" data-target="#actionModal">Create</button>
                        </div>
                    
                </div>
            </form>
           
       
    </div>
</div>
<!-- Modal -->
<div class="modal fade" id="actionModal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
       
    </div>
</div>
<script>
    $("#createbutton").click(function () {
        $.ajax({
            url: '@Url.Action("Action", "StayType")',

        })
            .done(function (response) {

                $("#actionModal .modal-dialog").html(response);

            })
                           
    });

     $(".data-btn").click(function () {
         $.ajax({
             url: $(this).attr("data-href"),

        })
            .done(function (response) {

                $("#actionModal .modal-dialog").html(response);

            })
                           
    });
</script>

HotelBooking/Areas/Dashboard/Views/StayType/_Action.cshtml
@model HotelBooking.Areas.Dashboard.ViewModels.StayTypeActionModels

@if (Model != null)
{
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title">Modal title</h5>
            @if (Model.Id > 0)
            {
                <span>Edit</span>
            }
            else
            {
                <span>Create</span>
            }
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            <form id="actionForm">
                <input type="hidden" name="Id" value="@Model.Id" /> 
                <div class="form-group">
                    <label>Name</label>
                    <input class="form-control" name="Name" placeholder="Enter Number" value="@Model.Name" >

                </div>
               
                <div class="form-group">
                    <label>Desc</label>
                    <textarea class="form-control" name="Desc" placeholder="Enter Description">@Model.Desc</textarea>
                </div>


            </form>
            <div class="errormes">

            </div>

        </div>
        <div class="modal-footer">
          
            <button  id="actionButton" type="button" class="btn btn-primary"data-dismiss="modal">Save changes</button>
        </div>
    </div>


}
<script>
    $("#actionButton").click(function () {

        $.ajax({
            url: '@Url.Action("Action", "StayType")',
            type: "post",
            data: $("#actionForm").serialize()
        })
            .done(function (response) {

                if (response.Success) {

                    location.reload();

                } else {
                    $(".errormes").html(response.Message)
                }

            });
    }); 
</script>

HotelBooking/Areas/Dashboard/Views/StayType/_Delete.cshtml
@model HotelBooking.Areas.Dashboard.ViewModels.StayTypeActionModels

@if (Model != null)
{
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title">Modal title</h5>
           
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            <form id="actionForm">
                <input type="hidden" name="Id" value="@Model.Id" />
           

              <div class="alert alert-danger" role="alert">
                  Are you sure?
              </div> 


            </form>
            <div class="errormes">

            </div>

        </div>
        <div class="modal-footer">
            @*<button id="actionButton" type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>*@
            <button  id="actionButton" type="button" class=" btn btn-primary"  data-dismiss="modal">Delete</button>
        </div>
    </div>


}
<script>
    $("#actionButton").click(function () {

        $.ajax({
            url: '@Url.Action("Delete", "StayType")',
            type: "post",
            data: $("#actionForm").serialize()
        })
            .done(function (response) {

                if (response.Success) {

                    location.reload();

                } else {
                    $(".errormes").html(response.Message)
                }

            });
    });
</script>

HotelBooking/Areas/Dashboard/Views/StayType/_Listenig.cshtml
@model HotelBooking.Areas.Dashboard.ViewModels.StayTypeListingModels

@if (Model != null && Model.StayTypes != null && Model.StayTypes.Count() > 0)
{
    <table class="table table-bordered">
        <thead>
            <tr>

                <th scope="col">Fullname</th>
                <th scope="col">Desc</th>
                <th scope="col">Actions</th>
            </tr>
        </thead>
        <tbody>

            @foreach (var staytype in Model.StayTypes)
            {
                <tr>

                    <td>@staytype.Name</td>

                    <td>@staytype.Desc</td>
                    <td>
                        <button data-href="@Url.Action("Action", "StayType", new {Id =staytype.Id}) "  type="button" class="data-btn btn btn-success"  data-toggle="modal" data-target="#actionModal">Edit</button>
                        <button  data-href="@Url.Action("Delete", "StayType", new {Id =staytype.Id}) " type="button" class="data-btn btn btn-danger"  data-toggle="modal" data-target="#actionModal">Delete</button>
                    </td>
                </tr>
            }


        </tbody>
    </table>

}
else
{
    <div class="alert alert-warning" role="alert">
       Otelde müştəri yooxdur!
    </div>
}

HotelBooking/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

HotelBooking/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

HotelBooking/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

HotelBooking/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>